<a href="https://colab.research.google.com/github/Bhumika-2294/ACM-task/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np

In [41]:
a = np.arange(12).reshape(3,4)

In [42]:
print(np.__version__)

2.0.2


In [43]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a.size

12

In [45]:
a.ndim

2

In [46]:
a.shape

(3, 4)

In [47]:
a.dtype

dtype('int64')

In [48]:
a.dtype.name

'int64'

In [49]:
a.real

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a.itemsize

8

In [51]:
type(a)

numpy.ndarray

In [52]:
b = np.array([7,8,9])

In [53]:
b

array([7, 8, 9])

In [54]:
type(b)

numpy.ndarray

In [55]:
b1 = np.array([1,2.3,2.4,7,8])

In [56]:
b1

array([1. , 2.3, 2.4, 7. , 8. ])

In [57]:
b

array([7, 8, 9])

In [58]:
b==b1

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [59]:
b!=b1

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [61]:
b1.dtype

dtype('float64')

In [62]:
b==b1.all()

array([False, False, False])

In [63]:
print(b==b1.all())

[False False False]


ValueError: operands could not be broadcast together with shapes (3,) (5,) 